### PR TITLE
Support for Scalingo 20 stack and sync from upstream

### PR DESCRIPTION
**Pull request by brandon-welsch**
## Changelog

- Add Support for Scalingo 20 Stack
- Sync from upstream
- Use correct arguments to unarchive tar.xz file (jvm-common-buildpack)
- Add `BUILDPACK_DEBUG`

### CODE REVIEW

**Review by curzolapierre — COMMENTED** [review]
Did you update the scalingo documentation too ? 
I think about the usage of `BUILD_CONFIG_WHITELIST`.

**Comment by brandon-welsch** [comment]
> BUILD_CONFIG_WHITELIST

Uh, no, this BUILD_CONFIG_WHITELIST was already present.

**Comment by brandon-welsch** [comment]
Ah, I have just realized what you mean. I will update the doc

**Comment by brandon-welsch** [comment]
Done: https://github.com/Scalingo/documentation/pull/1394

**Review by curzolapierre — APPROVED** [review]
LGTM

**Pull request merged**
